---

- hosts: vms
  gather_facts: no
  become: no
  vars_files: [../vars/main.yaml]
  tasks:
  - name: Ansible Controller Builds
    delegate_to: localhost
    become: no
    block:
          - name: Create kickstartHostConfigs Dir
            file: path=../{{Kickstart.path}} state=directory

          - name: Create Kickstart Files
            register: ks
            template:
              src: kickstart.cfg.j2
              dest: "../{{Kickstart.path}}/{{inventory_hostname }}.cfg"

          - name: Create kickstartIsos Dir
            file: path=../{{ISO.path}} state=directory

          - name: Build Kickstart Loaded ISO
            when: ks is changed
            delegate_to: localhost
            become: no
            connection: local
            command: chdir=../ ./build-configuration-iso.sh {{Kickstart.path}}/{{inventory_hostname}}.cfg {{ISO.path}}/local1.iso


  - name: Bastion Server VCenter Tasks
    delegate_to: '{{bastionHost}}'
    become: no
    block:
#          - vsphere_boot:
#              host: '{{ cmdb_parent }}'
#              login: '{{ esxlogin }}'
#              password: '{{ esxpassword }}'
#              guest: '{{ cmdb_uuid }}'
#              media: cdrom
#              image: '[nfs-datastore] /iso/ks/{{ inventory_hostname_short }}.iso'
#              state: boot_once

#          - name: upload ISO
#            vcenter_copy:
#              hostname: "{{ vcenter_hostname }}"
#              username: "{{ vcenter_username }}"
#              password: "{{ vcenter_password }}"
#              datacenter: "{{ vcenter_datacenter }}"
#              datastore: "{{ vcenter_datastore }}"
#              src: '{{ISO.path}}/{{ inventory_hostname }}.iso'
#              path: 'ISOs/{{ inventory_hostname }}.iso'

          - meta: end_play

#  - name: create vm
#    vcenter_guest:
#      vcenter_hostname: "{{ vcenter_hostname }}"
#      username: "{{ vcenter_username }}"
#      password: "{{ vcenter_password }}"
#      guest: "{{ inventory_hostname }}"
#      state: powered_on
#      vm_disk:
#        disk1:
#          size_gb: 16
#          type: thin
#          datastore: "{{ vcenter_datastore }}"
#      vm_nic:
#        nic1:
#          network: VM Network
#          type: vmxnet3
#          network_type: dvs
#      vm_hardware:
#        memory_mb: 2048
#        num_cpus: 2
#        osid: centos64Guest
#        scsi: paravirtual
#        vm_cdrom:
#          boot:
#            type: "iso"
#            iso_path: "{{ vcenter_datastore }}/boot.iso"
#          kickstart:
#            type: "iso"
#            iso_path: "{{ vcenter_datastore }}/ISOs/{{ inventory_hostname }}.iso"
